### PR TITLE
Update sabnzbd port

### PR DESCRIPTION
**Pull request by Silent-Remux**
# Pull request

**Purpose**
8080 conflicts with qbittorrent.

**Approach**
Makes it not conflict

**Open Questions and Pre-Merge TODOs**
Check all boxes as they are completed

- [ ] Use github checklists. When solved, check the box and explain the answer.

**Learning**
If you add a new template for a application take a look at [DockSTARTer](https://github.com/GhostWriters/DockSTARTer/tree/master/compose/.apps) for examples being I used them as base for the others templates

**Requirements**
Check all boxes as they are completed

- [ ] These changes meet the standards for [contributing](https://github.com/TRaSH-/Guides-Synology-Templates/blob/main/.github/CONTRIBUTING.md).
- [ ] I have read the [code of conduct](https://github.com/TRaSH-/Guides-Synology-Templates/blob/main/.github/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by bokkoman** [comment]
I agree with this. What port would be a good one?

**Comment by acme64** [comment]
8090?

**Comment by TRaSH-** [comment]
8085?

**Comment by bokkoman** [comment]
8880. 7070. 8111.
Can be anything.

**Comment by NickFranceschina** [comment]
just ran into this... re-open and merge?

**Comment by bokkoman** [comment]
> just ran into this... re-open and merge?

No we are not going to change the default port 
You can change it yourself in the docker-compose.yml. It's also mentioned in this thread.

**Pull request closed without merging**
