### PR TITLE
Added template for Jellyfin

### PR DESCRIPTION
**Pull request by Zelaf**
A template for Jellyfin based on the template for Plex. I've removed some options that are made for the Plex container and changed anything plex related to Jellyfin

# Pull request

**Purpose**
I want to add a Jellyfin template so people who use Jellyfin don't have to modify or create a new compose.

**Approach**
Edited the existing Plex template

**Open Questions and Pre-Merge TODOs**
Check all boxes as they are completed

- [ ] Use github checklists. When solved, check the box and explain the answer.

**Learning**
If you add a new template for a application take a look at [DockSTARTer](https://github.com/GhostWriters/DockSTARTer/tree/master/compose/.apps) for examples being I used them as base for the others templates

**Requirements**
Check all boxes as they are completed

- [*] These changes meet the standards for [contributing](https://github.com/TRaSH-/Guides-Synology-Templates/blob/main/.github/CONTRIBUTING.md).
- [*] I have read the [code of conduct](https://github.com/TRaSH-/Guides-Synology-Templates/blob/main/.github/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by BaukeZwart** [comment]
Please check the template, there a few references to Plex and the ports are incorrect.

**Comment by Zelaf** [comment]
My bad! It's fixed now tho!

**Comment by bokkoman** [comment]
> My bad! It's fixed now tho!

Is that the correct port? I thought JF uses something else.

**Comment by Zelaf** [comment]
Jesus, remind me to not do commits when in a rush lol. It should be fine now thanks for noticing!

**Pull request merged**
