### PR TITLE
Create rtorrentvpn config file for Synology

### PR DESCRIPTION
**Pull request by andrewjmetzger**

### CODE REVIEW

**Comment by andrewjmetzger** [comment]
By default, the variables `RPC2_PASS` (for communicating with *arrs) and `WEBUI_PASS` (for management) are just defined in the compose file. Should these be separated into `.env`?

My initial thought was "no", because they only apply to rtorrentvpn, but I'm curious to hear your opinion.

**Comment by TRaSH-** [comment]
> By default, the variables `RPC2_PASS` (for communicating with *arrs) and `WEBUI_PASS` (for management) are just defined in the compose file. Should these be separated into `.env`?
> 
> My initial thought was "no", because they only apply to rtorrentvpn, but I'm curious to hear your opinion.

I think it might be better to add this to the .env so the user only needs to edit the .env and don't need to touch the .yml file.
also being that some settings some users don't want.

i'm even considering to make the same changes/updates for qbtvpn and delugevpn.

I already made the changes to for the .env
let me know if you think everything is correct like this.

I did find in another compose for rtorrentvpn the following entry
```yml
services:
  rtorrentvpn:
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
```
But i'm not sure if you need need `SYS_MODULE` with a synology ?
perhaps something you can test ?

**Comment by TRaSH-** [comment]
i changed to webgui port also to the official one 9080

**Comment by andrewjmetzger** [comment]
Looks good with things in `.env`, Thanks for updating the port number, can't believe I missed that! 🤦 

As far as I know, `SYS_MODULE` is only used to add the Wireguard kernel modules to systems that don't support it out of the box. On Synology boxes, that's a pain, so its suggested to just use OpenVPN, which doesn't require `SYS_MODULE`.

**Pull request merged**
